services:
  - type: web
    name: google-form-automation
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: CHROME_BIN
        value: /usr/bin/chromium-browser
