services:
  - type: web
    name: google-form-automation
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn_config.py app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: CHROME_BIN
        value: /usr/bin/chromium-browser
